language: python
python:
  - "3.3"
#  - "3.4"
#  - "3.5"

# Don't do CI for WIP branches
branches:
  except:
    - /^WIP-.*$/

sudo: false

setup:
  - git fetch --unshallow && git fetch --tags
  - git describe

script:
  - python setup.py test
  - python setup.py install
  - python setup.py pep8 || true
  - for DIR in $(find -name test -type d); do (cd $DIR; make); done
