#
# This file is part of LiteVideo.
#
# Copyright (c) 2026 Tim 'mithro' Ansell <me@mith.ro>
# SPDX-License-Identifier: BSD-2-Clause

"""BCH ECC of HDMI data island packets.

HDMI 1.3 §5.2.3.5: "BCH(64,56) and BCH(32,24) are generated by the polynomial
G(x) shown in Figure 5-5. G(x)=1+x6+x7+x8". Bits enter LSB first (bit 0 of
HB0/SB0 first, §5.2.3.4 Figure 5-4). The generator is implemented as a
reflected right-shifting LFSR: each data bit is XORed with the register LSB,
the register shifts right, and the feedback XORs in the reflected polynomial
mask 0x83 (= 0xC1 bit-reversed). This is exactly the ``next_ecc`` function of
hdl-util/hdmi ``src/packet_assembler.sv``.

The header ECC covers 24 bits; each subpacket ECC covers 56 bits. Both are
transmitted after their data, LSB first, as the last 8 characters of the
packet (header: 1 bit per character on channel 0 bit 2; subpackets: 2 bits
per character on channels 1 and 2).
"""

from migen import *

BCH_POLYNOMIAL = 0x1C1   # x^8 + x^7 + x^6 + 1
BCH_LFSR_MASK  = 0x83    # low byte of the polynomial, bit-reversed


def bch_ecc(data_bytes):
    """Python reference: ECC over ``data_bytes`` (list of ints), LSB first."""
    ecc = 0
    for byte in data_bytes:
        for i in range(8):
            feedback = (ecc ^ (byte >> i)) & 1
            ecc >>= 1
            if feedback:
                ecc ^= BCH_LFSR_MASK
    return ecc


def bch_step(state, bit):
    """Migen expression: next 8-bit LFSR state after feeding one data bit."""
    feedback = state[0] ^ bit
    return Cat(state[1:], 0) ^ (Replicate(feedback, 8) & C(BCH_LFSR_MASK, 8))
